# Generated by Django 5.1.2 on 2025-03-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='telegram',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
