# Generated by Django 5.1.2 on 2025-03-19 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jugador_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros', to='core.equipo'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='legajo',
            field=models.CharField(max_length=40),
        ),
    ]
