# Generated by Django 5.1.2 on 2025-03-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_jugador_equipo_alter_jugador_foto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='aprobado',
        ),
        migrations.AddField(
            model_name='equipo',
            name='estadoAprobacion',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('En revisión', 'En revisión'), ('Pago pendiente', 'Pago de inscripción pendiente')], default='Pago pendiente', max_length=20),
        ),
    ]
