# Generated by Django 5.1.2 on 2025-03-21 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_equipo_aprobado_equipo_estadoaprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='capitan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_capitan', to='core.jugador'),
        ),
    ]
