# Generated by Django 5.1.2 on 2025-03-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_equipo_capitan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='legajo',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
