# Generated by Django 5.1.2 on 2025-03-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_jugador_legajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del clip', max_length=100)),
                ('url', models.URLField(help_text='URL completa del clip de Twitch')),
                ('activo', models.BooleanField(default=True, help_text='¿Este clip está activo y debe mostrarse en el carrusel?')),
            ],
        ),
    ]
