# Generated by Django 5.1.2 on 2025-03-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_twitchclip'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='edicion_habilitada',
            field=models.BooleanField(default=True),
        ),
    ]
