# Generated by Django 5.1.2 on 2025-03-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_jugador_edicion_habilitada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='legajo',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
