# Generated by Django 5.1.2 on 2025-03-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_jugador_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='inscripciones_habilitadas',
            field=models.BooleanField(default=True),
        ),
    ]
