# Generated by Django 5.1.2 on 2025-03-27 18:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_staff_inscripciones_habilitadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='comprobante_pago',
            field=models.ImageField(
                upload_to=core.models.generar_ruta_unica_comprobante),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='logo',
            field=models.ImageField(
                upload_to=core.models.generar_ruta_unica_logo),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='foto',
            field=models.ImageField(
                null=True, upload_to=core.models.generar_ruta_unica_jugador),
        ),
    ]
